name: Build and Deploy

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Build & Push Docker Image to Docker Hub, then deploy to production server'
        required: true
        default: 'Manual build from GitHub UI'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  app-name: "cd-website"

jobs:
  build:
    runs-on: [ self-hosted ]
  
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      
      - run: yarn install
      - run: yarn build
      - run: yarn test
      
  deploy:
    needs: build
    runs-on: [ self-hosted ]
    defaults:
      run:
        working-directory: '/home/quochao/website'
    
    steps:
      - name: Pull code
        working-directory: '/home/quochao/website/website-client'
        run: git pull origin master
        
      - name: Build and run
        run: docker compose up -d --build
